---
id: Oauth
name: Oauth
full: OAuth client library
description: >-
  A library that provides an OAuth consumer (http://oauth.net) and OAuth infrastructure, and in the
  future will provide an OAuth server.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Oauth
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 2.0.5
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Util: ^2
    ext:
      hash: '*'
      openssl: '*'
