---
id: Oauth
name: Oauth
full: OAuth client library
description: >-
  A library that provides an OAuth consumer (http://oauth.net) and OAuth
  infrastructure, and in the future will provide an OAuth server.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Oauth
authors:
  -
    name: Chuck Hagenbuch
    user: chuck
    email: chuck@horde.org
    active: false
    role: lead
version:
  release: 3.0.0alpha2
  api: 1.0.0
state:
  release: alpha
  api: stable
license:
  identifier: BSD-2-Clause
  uri: http://www.horde.org/licenses/bsd
dependencies:
  required:
    php: ^7
    composer:
      horde/exception: ^3
      horde/http: ^3
      horde/util: ^3
    ext:
      hash: '*'
      openssl: '*'
